### ISSUE TITLE
[README] Improve the references to code

### ISSUE THREAD

**Issue by tlylt** [wilsonngja/MeetUps#21]
1. The reference to code should be sparse, only when important. This is because code is bound to change and copy-pasting the entire file is unlikely to give any insights into the technical details. Efforts should be put into explaining the important aspects of selected functionalities, not the entire implementation.
2. When you do use images, try https://carbon.now.sh/ (Some of the existing images are hardly readable)

**Comment by wilsonngja** [comment]
The newest README has higher level of explanation with minimum code level explanation :)
