### ISSUE TITLE
[UI] Make website responsive

### ISSUE THREAD

**Issue by tlylt** [wilsonngja/MeetUps#22]
At the moment, the website seems to break down if the width of the screen is smaller:
![image](https://user-images.githubusercontent.com/41845017/175973758-674f9f39-44b2-43a3-8d6f-b7ec756185b0.png)
![image](https://user-images.githubusercontent.com/41845017/175973809-dafb6c88-0ecc-4bdc-8404-802ad89777fa.png)

While some effort is required, it would be great if the website can be responsive (i.e, usable across different screen sizes).

Some information if you are not familiar (basically you need some CSS)
https://kinsta.com/blog/responsive-web-design/
https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design

**Comment by wilsonngja** [comment]
![image](https://user-images.githubusercontent.com/31720838/177701092-5a8ac28b-f597-454b-993a-3ecac54a1b7c.png)
![image](https://user-images.githubusercontent.com/31720838/177701122-def3c5e4-7173-4292-aee3-b26973ac3b47.png)

Made to be more responsive
