### ISSUE TITLE
[UI] Better use of color

### ISSUE THREAD

**Issue by tlylt** [wilsonngja/MeetUps#24]
Currently, the choice of color seems arbitrary. However, some standard use of colors will make the website more user-friendly. For example:
- Use the same color for the same type of things (problem: now a lot of purple for all the clickable elements)
- Use different colors for different things
- Use common colors to signal system state (RED for error messages, GREEN for successful operations)

**Comment by wilsonngja** [comment]
![image](https://user-images.githubusercontent.com/31720838/177701299-80db70fb-3aa0-410f-a8ad-5c890ebf4ab6.png)

Red colours added for error messages

![image](https://user-images.githubusercontent.com/31720838/177701433-3cc00905-94eb-4ca1-9615-860abcac77dc.png)
Button has also change with hover effect
