### ISSUE TITLE
[UI] Consider separating timeslot and venue search into separate pages

### ISSUE THREAD

**Issue by tlylt** [wilsonngja/MeetUps#26]

**Comment by wilsonngja** [comment]
Separated into different pages by tabs.
![image](https://user-images.githubusercontent.com/31720838/177474590-0a800ef1-2f4e-46e7-9b41-d4e52b520335.png)
![image](https://user-images.githubusercontent.com/31720838/177474605-7ad131ae-2670-4f0a-b0fa-eeb32cb72c60.png)
