### ISSUE TITLE
[UI] Missing "Sunday" option?

### ISSUE THREAD

**Issue by tlylt** [wilsonngja/MeetUps#29]
![image](https://user-images.githubusercontent.com/41845017/175979620-c50028e4-100a-4920-a035-8b94f62223ac.png)

**Comment by wilsonngja** [comment]
Hi, Sunday wasn't included because there isn't any lesson on Sunday. Would this current display be okay or do I have to do something else?

**Comment by wilsonngja** [comment]
Because when we are assuming that if there is no lesson at all, the rooms will be locked, thus not able to access.
Or would it be okay if it can be placed in the description or something similar?

**Comment by tlylt** [comment]
> Because when we are assuming that if there is no lesson at all, the rooms will be locked, thus not able to access. Or would it be okay if it can be placed in the description or something similar?

Ah ok I didn't know that 😓. Yup I think if it can be included in some description would be great!

**Comment by wilsonngja** [comment]
Alright! I will discuss with @chinhan99 and see how we can include this as part of the user interface. Thank you :)

**Comment by wilsonngja** [comment]
![image](https://user-images.githubusercontent.com/31720838/177474412-06359f4e-58c8-4d76-9b00-42948d4f0a91.png)

^
Added the message as shown above.
