### ISSUE TITLE
[UI] Missing error handling for empty start and end time

### ISSUE THREAD

**Issue by tlylt** [wilsonngja/MeetUps#30]
![image](https://user-images.githubusercontent.com/41845017/175980156-b4899cd3-35e4-46ab-8c37-51a2ffa55fbc.png)

Nothing happens if I click on find venue without start and end time

**Comment by wilsonngja** [comment]
![image](https://user-images.githubusercontent.com/31720838/176728855-38f3cada-4ceb-4bad-b3eb-0b2f8a42f788.png)
![image](https://user-images.githubusercontent.com/31720838/176728886-bda02e96-06ff-448d-ad41-e74e4902f14e.png)
![image](https://user-images.githubusercontent.com/31720838/176728923-75d7b37f-75a3-4ad8-9913-6e0f89579f60.png)

Fixed the bug and made more explicit error message
